import type { Metadata } from "next";
import "./styles/style.scss";
import Links from "./comps/links"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Links />
        {children}
      </body>
    </html>
  );
}
